#!/usr/bin/env node
/* =====================================================================
   CasBadge3D — lock builder
   ---------------------------------------------------------------------
   Encrypts the plaintext engine (_src/app.js) with a staff pass code and
   writes ../app.enc.js (the only engine file the public site ships).

   The pass code is NEVER stored anywhere. It is run through PBKDF2 to
   derive an AES-GCM key; only someone who types the correct code in the
   browser can decrypt and run the tool. To ROTATE the code, just run this
   again with a new one and commit the new app.enc.js.

   USAGE
     node lock-build.mjs "YourNewStaffCode"      # code as an argument
     CB_CODE="YourNewStaffCode" node lock-build.mjs
     node lock-build.mjs                          # prompts for the code

   Requires Node 16+ (uses the built-in Web Crypto API). No npm installs.
   ===================================================================== */

import { webcrypto as crypto } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";

const HERE      = dirname(fileURLToPath(import.meta.url));
const SRC_PATH  = join(HERE, "app.js");           // plaintext engine (this folder)
const OUT_PATH  = join(HERE, "..", "app.enc.js");  // encrypted blob (served)

// --- crypto parameters (MUST match gate.js) ---------------------------
const ITER = 250000;
const HASH = "SHA-256";
const SALT_BYTES = 16;
const IV_BYTES   = 12;

const b64 = (buf) => Buffer.from(buf).toString("base64");

async function getCode() {
  const fromArg = process.argv[2];
  const fromEnv = process.env.CB_CODE;
  if (fromArg && fromArg.trim()) return fromArg.trim();
  if (fromEnv && fromEnv.trim()) return fromEnv.trim();
  const rl = createInterface({ input: stdin, output: stdout });
  const ans = (await rl.question("New staff pass code: ")).trim();
  rl.close();
  return ans;
}

async function main() {
  const code = await getCode();
  if (!code) { console.error("No pass code given — aborting."); process.exit(1); }
  if (code.length < 6) console.warn("⚠  That code is short; 10+ characters is safer against guessing.");

  const plaintext = await readFile(SRC_PATH);

  const salt = crypto.getRandomValues(new Uint8Array(SALT_BYTES));
  const iv   = crypto.getRandomValues(new Uint8Array(IV_BYTES));

  const baseKey = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(code), "PBKDF2", false, ["deriveKey"]
  );
  const key = await crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations: ITER, hash: HASH },
    baseKey,
    { name: "AES-GCM", length: 256 },
    false, ["encrypt"]
  );
  const ct = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, plaintext);

  const payload = {
    v: 1, kdf: "PBKDF2", hash: HASH, iter: ITER,
    salt: b64(salt), iv: b64(iv), ct: b64(ct),
  };

  const banner =
`/* CasBadge3D encrypted engine — generated by _src/lock-build.mjs
   This is ciphertext. It only decrypts with the current staff pass code,
   entered in the browser. Do NOT commit _src/app.js to the public site. */
`;
  await writeFile(OUT_PATH, banner + "window.__CB_LOCK = " + JSON.stringify(payload) + ";\n");

  console.log("✅ Wrote", OUT_PATH);
  console.log("   engine:", plaintext.length, "bytes  →  blob:", payload.ct.length, "b64 chars");
  console.log("   PBKDF2 iterations:", ITER, "| hash:", HASH);
  console.log("\nNext: commit app.enc.js (and index.html/gate.js the first time) and push.");
}

main().catch((e) => { console.error(e); process.exit(1); });
